### ISSUE TITLE
Remove `_decimals` parameter from the constructor and hard code it to 18

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#10]
Since we [use the `ether` unit](https://github.com/poanetwork/dpos-token/blob/2921d90745710b2e774af5895bf8d082cb26c905/contracts/Distribution.sol#L85-L90) in the `Distribution` contract, let's hard code `decimals` to `18` because `ether` has 18 decimals.

**Comment by maxaleks** [comment]
Fixed in https://github.com/poanetwork/dpos-token/commit/0d6542284b5e73fe9aa00ff2f8fcd1b780a8637e

**Comment by varasev** [comment]
Please don't close issues until I review them. It's more convenient to keep them open and only close when they are checked.
