### ISSUE TITLE
Actualize docs

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#11]
Seems the updated code partially contains old docs. E.g., `Distribution` [constructor](https://github.com/poanetwork/dpos-token/blob/2921d90745710b2e774af5895bf8d082cb26c905/contracts/Distribution.sol#L70). The [`changePoolAddress`](https://github.com/poanetwork/dpos-token/blob/2921d90745710b2e774af5895bf8d082cb26c905/contracts/Distribution.sol#L190) function has no docs at all. The docs for `unlockRewardForStaking` should contain some info about `approve` ERC20 call needed before calling this function (you can take it from [this comment](https://github.com/poanetwork/dpos-token/issues/6#issuecomment-513197659)).

**Comment by varasev** [comment]
Please also write docs for events and public state variables.

**Comment by maxaleks** [comment]
Updated in https://github.com/poanetwork/dpos-token/commit/1fe0f7079909cbdbd41d3910874998f9f1837980

**Comment by varasev** [comment]
The comments inside the `Distribution` contract are now fine, but we also need to update the comments for `ERC677BridgeToken`.

**Comment by maxaleks** [comment]
Updated in https://github.com/poanetwork/dpos-token/commit/b5a1a1b49037bad2425313a895c7a6654e5cd2d4
