### ISSUE TITLE
make_flat script sets `pragma solidity ^0.5.0` for Distribution_flat.sol

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#12]
The reason is that the `Distribution` contract imports https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.3.0/contracts/ownership/Ownable.sol which contains `pragma solidity ^0.5.0;` instead of expected `pragma solidity 0.5.10;`.

We need to make `solidity-flattener` use the first pragma directive (the [first line](https://github.com/poanetwork/dpos-token/blob/2921d90745710b2e774af5895bf8d082cb26c905/contracts/Distribution.sol#L1) in the `Distribution` contract for this case).

**Comment by vbaranov** [comment]
@varasev @maxaleks I made a fix in `solidity-flattener` to correctly identify the first pragma occurrence. Please let me know if it works for you. If so, I will merge it to master.

**Comment by varasev** [comment]
@vbaranov now it's OK, thanks!

**Comment by varasev** [comment]
Let's wait for https://github.com/poanetwork/solidity-flattener/pull/32 to be merged before closing this issue.
