### ISSUE TITLE
Describe deployment order in README

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#14]
Please add info about deployment order to the README. Example:

1) Deploy `Distribution` contract. Pass the addresses of all participants and private offering participants stake amounts to its constructor.

2) Deploy ERC677 contract. The total supply is minted at that moment to the `Distribution` contract address.

3) Call `initialize` function of the `Distribution` contract. It releases `Public Offering`, `Exchange Related Activities`, and 25% of `Private Offering` tokens. The countdown for cliff periods and installments starts from this moment.

**Comment by maxaleks** [comment]
Added in https://github.com/poanetwork/dpos-token/commit/9855d2a048fe2db8b1a535d2741609efb2575d2e
