### ISSUE TITLE
Move bridge address initialization from the constructor to a separate function

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#15]
Since we cannot know an address of the bridge when deploying or initializing the `Distribution` contract, let's pass bridge address through some separate function instead of passing it into the constructor. Such a function must only be callable by an owner and must check the passed address with `_isContract`.

Please also add `require(bridgeAddress != address(0))` to the `unlockRewardForStaking ` function.

**Comment by maxaleks** [comment]
Fixed in https://github.com/poanetwork/dpos-token/commit/10e71bf8b2eb672e7ec313b1b5d49c337337ef97
