### ISSUE TITLE
Create interfaces and import them instead of importing contracts

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#17]
In the `Distribution` contract [the whole `ERC677BridgeToken` contract is imported](https://github.com/poanetwork/dpos-token/blob/8d11bcc1e6c7db992409ff57173f9c2f6dfe93f4/contracts/Distribution.sol#L5).

Let's create an interface `IERC677BridgeToken` (containing `balanceOf`, `transfer`, and `transferFrom` functions) and import that instead because the current contract's importing includes an excess code into the code of `Distribution` (it is seen when we create a flat source file).

The same goes for [importing the `Distribution` by `ERC677BridgeToken`](https://github.com/poanetwork/dpos-token/blob/8d11bcc1e6c7db992409ff57173f9c2f6dfe93f4/contracts/Token/ERC677BridgeToken.sol#L9): let's have `IDistribution` interface.

Without these changes, flat versions of the contracts look ugly with redundant code.

Don't forget to inherit `ERC677BridgeToken` from `IERC677BridgeToken` and `Distribution` from `IDistribution` to make sure that possibly changed (in the future) interface's abstract functions will correspond to their implementations (for example, see `posdao-contracts` repo).

**Comment by maxaleks** [comment]
Added in https://github.com/poanetwork/dpos-token/commit/bb7a3d1f4516550413b22e68c693e6adda890fbe
