### ISSUE TITLE
valueAtCliff[PRIVATE_OFFERING] must be 25% of stake[PRIVATE_OFFERING]

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#18]
Seems there is an outdated percent value on [this line](https://github.com/poanetwork/dpos-token/blob/8d11bcc1e6c7db992409ff57173f9c2f6dfe93f4/contracts/Distribution.sol#L133). The [spreadsheet](https://docs.google.com/spreadsheets/d/1FjxsgtWjhbHF7IXOuk5kr4X6aMYwM4ms02wUoj6i_oo/edit#gid=0) shows that there must be 25% (see `D5` cell).

**Comment by maxaleks** [comment]
@varasev 25% are distributed here: https://github.com/poanetwork/dpos-token/blob/8d11bcc1e6c7db992409ff57173f9c2f6dfe93f4/contracts/Distribution.sol#L170
10% are here in the spreadsheet: https://docs.google.com/spreadsheets/d/1FjxsgtWjhbHF7IXOuk5kr4X6aMYwM4ms02wUoj6i_oo/edit#gid=1465020438&range=J6

**Comment by varasev** [comment]
Ah, right, thanks.
