### ISSUE TITLE
Add a tag v1.0.0 (for docs)

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#2]
Please add a new tag `v1.0.0` (the version must be the same as defined in the [`package.json`](https://github.com/poanetwork/dpos-token/blob/f85b63684be6df6fa82bc5ae6bca673f414c1918/package.json#L3)) to make links in the [docs](https://poanetwork.github.io/dpos-token/docs/) work correctly. Example: https://github.com/poanetwork/dpos-token/blob/v1.0.0/contracts/Distribution.sol (shows 404 error at the moment).

**Comment by maxaleks** [comment]
The tag `v1.0.0` was added

**Comment by varasev** [comment]
Please recreate this tag so that it would point to the latest commit.
