### ISSUE TITLE
remainder inside the `makeInstallment` function

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#22]
We see that there can be [`remainder`](https://github.com/poanetwork/dpos-token/blob/8d11bcc1e6c7db992409ff57173f9c2f6dfe93f4/contracts/Distribution.sol#L234) when distributing installments.

Seems the remainder can also be after [`_distributeTokensForPrivateOffering` function working](https://github.com/poanetwork/dpos-token/blob/8d11bcc1e6c7db992409ff57173f9c2f6dfe93f4/contracts/Distribution.sol#L237).

I'd propose to calculate that as well and then return it to `stake[PRIVATE_OFFERING]`.

**Comment by maxaleks** [comment]
Fixed in https://github.com/poanetwork/dpos-token/commit/85edf0db060aa42f4fca16128029d3668887ac90

**Comment by varasev** [comment]
@maxaleks There are too many changes in that commit, so they require to review the entire code. Could you please revert the changes from https://github.com/poanetwork/dpos-token/commit/85edf0db060aa42f4fca16128029d3668887ac90 and then add them again through opening a pull request. I'm not sure they are all required for this fix. We just need to calculate remainder inside the `_distributeTokensForPrivateOffering` and add it to stake[PRIVATE_OFFERING] (there should be 3-4 lines of code changed).

**Comment by varasev** [comment]
Done in #28.
