### ISSUE TITLE
Remove ERC677Receiver.sol and ERC677.sol contracts

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#24]
Since `ERC677Receiver` is not used, let's remove it. BTW, we can also remove its inheritance from `test/mocks/RecipientMock.sol`.

Also, I'm not sure we need to have `ERC677.sol` because it only describes the `Transfer` event and `transferAndCall` function which is already defined in the `ERC677BridgeToken`. The extended `Transfer` event declaration could be moved to `ERC677BridgeToken`.

**Comment by maxaleks** [comment]
Removed in https://github.com/poanetwork/dpos-token/commit/d66c19e2ef86137e5b28d467d809515f0651b335
