### ISSUE TITLE
Use `isContract` from openzeppelin's `Address` library

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#25]
Let's remove the `_isContract` internal function and use the `Address` library which is already included in `SafeERC20`. Example:

```solidity
    ...
    using Address for address;
    ...
    _to.isContract()
    ....
```

**Comment by maxaleks** [comment]
Fixed in https://github.com/poanetwork/dpos-token/commit/cd45649db324b6529b77fdfbaca7a60b4bf6a4ec
