### ISSUE TITLE
Test deployment script

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#29]
Let's test the deployment implemented in https://github.com/poanetwork/dpos-token/blob/dev/migrations/2_deploy_contracts.js on some test network (Sokol or Kovan) and add an example of CLI command for that into README.

Also, I think we should comment out [this line](https://github.com/poanetwork/dpos-token/blob/9855d2a048fe2db8b1a535d2741609efb2575d2e/migrations/2_deploy_contracts.js#L40) as the initialization is not supposed to be done immediately after deployment.

**Comment by maxaleks** [comment]
Added in https://github.com/poanetwork/dpos-token/commit/66cda065a4ab4697f4d23598bb034aa1d26e5210, https://github.com/poanetwork/dpos-token/commit/f238389b7b422724a2568ececf23d4bea1075f9e
