### ISSUE TITLE
Flat files generation script

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#3]
Please add a script to generate flatten sources of smart contracts (like the [`npm run flat`](https://github.com/poanetwork/posdao-contracts/blob/2bea6eff35dfe6c224be0819a40df471b1f54ca6/package.json#L8) command in the [`posdao-contracts`](https://github.com/poanetwork/posdao-contracts) repo). Such a script could be useful to see the entire code of the token contract in a single solidity source file.

**Comment by maxaleks** [comment]
Added in: https://github.com/poanetwork/dpos-token/commit/81beb002f6f839ce535d33b4cc86812e409d180f, https://github.com/poanetwork/dpos-token/commit/905192f945a7b2bda08dd9b6ab999a9bc801ca47
