### ISSUE TITLE
Make state variables public in Distribution.sol

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#4]
Let's make these variables, mappings, and constants public:
- https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L11
- https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L19-L37

**Comment by maxaleks** [comment]
Fixed in https://github.com/poanetwork/dpos-token/commit/852709375b69af2e3b0aefe271608f730dd108bc
