### ISSUE TITLE
Restrict sending tokens to the `Distribution` and `PrivateOfferingDistribution` contracts

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#45]
The current code allows anyone to send their tokens to the `Distribution` and `PrivateOfferingDistribution` contracts.

Seems when someone sends their tokens that way, this is equivalent of burning them because these tokens will forever be on the balance of `Distribution` or `PrivateOfferingDistribution` contract.

I think we should restrict doing that. To do that, we need to

1) Add the following lines to `ERC677BridgeToken._callAfterTransfer` function right after [this line](https://github.com/poanetwork/dpos-token/blob/aff6b9ec543c9f393c34a34f170920b53e42b4fb/contracts/Token/ERC677BridgeToken.sol#L179):

    ```solidity
    require(_to != distributionAddress, "you can't transfer to Distribution contract");
    require(_to != privateOfferingDistributionAddress, "you can't transfer to PrivateOfferingDistribution contract");
    ```

2) Add `Distribution.onTokenTransfer` which will restrict sending tokens to the `Distribution` contract:

    ```solidity
    function onTokenTransfer(address, uint256, bytes memory) public pure returns(bool) {
        revert();
    }
    ```

    We already have `PrivateOfferingDistribution.onTokenTransfer` function which will restrict sending tokens to `PrivateOfferingDistribution` when the step `1` above is implemented.

3) Add unit tests which should cover such cases.

@maxaleks @igorbarinov do you agree we should disallow sending tokens to these distribution contracts?

If not, we need to add unit tests for the cases when someone sends their tokens to the distribution contracts, and these tests should ensure that nothing is broken in the current distribution scheme for such cases.

For example, if someone transfers tokens to the `PrivateOfferingDistribution`, its balance will be increased but the [`maxBalanceForCurrentEpoch`](https://github.com/poanetwork/dpos-token/blob/aff6b9ec543c9f393c34a34f170920b53e42b4fb/contracts/PrivateOfferingDistribution.sol#L181) variable won't be affected because `onTokenTransfer` fails (due to [this requirement](https://github.com/poanetwork/dpos-token/blob/aff6b9ec543c9f393c34a34f170920b53e42b4fb/contracts/PrivateOfferingDistribution.sol#L180)). Seems this doesn't break anything, do you agree @maxaleks ?

**Comment by maxaleks** [comment]
@varasev I agree with this proposal. We need this restriction to avoid possible issues

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/dpos-token/pull/46.
