### ISSUE TITLE
Private Offering stakes validation and their total sum

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#5]
The current version of `Distribution` contract assumes that the total amount of the `Private Offering` stakes which will be passed to the [`initialize`](https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L108-L109) function must be [strictly equal](https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L245) to the value defined in `Distribution!B5` cell of the spreadsheet https://docs.google.com/spreadsheets/d/1FjxsgtWjhbHF7IXOuk5kr4X6aMYwM4ms02wUoj6i_oo

I.e. if there are `8471184` tokens for `Private Offering`, that means that private investors must stake exactly the same amount in total.

Is that correct? @igorbarinov 

I suspect that the stakes array which we will pass to the [`initialize function through _privateOfferingParticipantsStakes array`](https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L109) is not related to the total amount defined for `Private Offering` in the `Distribution!B5` cell.

**Comment by igorbarinov** [comment]
> that means that private investors must stake exactly the same amount in total.

they will receive this amount or less. 
will they stake or not we don't know. 
it's possible that 0 tokens will be used for staking from this distribution.

**Comment by varasev** [comment]
OK, if there are at most `8 471 184` private tokens possible and we only have two investors:

- investor `A` who has `3 000 000` in the `_privateOfferingParticipantsStakes` array
- investor `B` who has `2 000 000` in the `_privateOfferingParticipantsStakes` array

then we consider that:

- investor `A` will receive `3 000 000` / `8 471 184` = `35.4%` of Private Offering
- investor `A` will receive `2 000 000` / `8 471 184` = `23.6%` of Private Offering
- nobody receives the rest `41%` of Private Offering

Am I right?

Or should we determine their shares based on their total sum of `3 000 000` + `2 000 000` = `5 000 000`? In that case:

- investor `A` will receive `3 000 000` / `5 000 000` = `60%` of Private Offering
- investor `B` will receive `2 000 000` / `5 000 000` = `40%` of Private Offering

Which calculation is more correct?

**Comment by igorbarinov** [comment]
All private buyers and their shares will be known before 
If less buyers participate in private then private distribution will be smaller and ecosystem fund bigger

**Comment by varasev** [comment]
> All private buyers and their shares will be known before
> If less buyers participate in private then private distribution will be smaller and ecosystem fund bigger

Thanks, now it's clear.

@maxaleks I think it's better to move private fund initialization from the `initialize` function to the constructor to be able to calculate `stake[ECOSYSTEM_FUND]` considering the total sum in the `_privateOfferingParticipantsStakes`.

**Comment by maxaleks** [comment]
Fixed in https://github.com/poanetwork/dpos-token/commit/b0c009a579e2157a35e9dca8040fba770cb59380
