### ISSUE TITLE
unlockRewardForStaking function and msg.sender

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#6]
It seems that the current version of the [`unlockRewardForStaking`](https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L137) function transfers `73 000 000` tokens from the `Distribution` contract address to the bridge contract address.

The problem here is that token sending to the bridge contract will be done from the `Distribution` contract address. So, we won't be able to send the `reward for staking` tokens to zero address (burn them) on xDai side because we can't know the private key of the `Distribution` contract address. Here we should somehow pass our multisig address to the `Transfer` event (in its `from` field) or pass `address(0)` there, as I [wrote about it earlier](https://github.com/poanetwork/dpos-token/commit/5b78a69a7f3658ec6ff066e04071742cae4bbf58#r34120535).

**Comment by varasev** [comment]
To be able to properly emit the `Transfer` event for the bridge, I suggest to replace [the line](https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L141)

```solidity
token.transfer(_bridgeAddress, stake[REWARD_FOR_STAKING]);
```

with

```solidity
token.transfer(poolAddress[REWARD_FOR_STAKING], stake[REWARD_FOR_STAKING]);
token.transferFrom(poolAddress[REWARD_FOR_STAKING], _bridgeAddress, stake[REWARD_FOR_STAKING]);
```

This will emit the `Transfer(poolAddress[REWARD_FOR_STAKING], _bridgeAddress, 73000000)` event which will be caught by the `erc-to-erc` bridge, and the bridge will mint `73000000` tokens for the `poolAddress[REWARD_FOR_STAKING]` multisig on xDai side, and then the multisig on xDai side would call `transfer(0, 73000000)` to burn the tokens on xDai side.

Note that this solution requires two additional things:

1. Before calling the `Distribution.unlockRewardForStaking` the multisig must call the [`approve`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v2.3.0/contracts/token/ERC20/ERC20.sol#L79) function with the following parameters:
- `spender` = `Distribution` address
- `value` = `73 000 000`

2. We must initialize `poolAddress[REWARD_FOR_STAKING]` by our multisig address in the [`initialize`](https://github.com/poanetwork/dpos-token/blob/280c58429e0081069d106a1a7defeb46e58bdd5d/contracts/Distribution.sol#L103) function.

**Comment by maxaleks** [comment]
Fixed in https://github.com/poanetwork/dpos-token/commit/3309adc6a76f353c1f6258b7631cbe9aa3af5f68
