### ISSUE TITLE
Add events for Distribution contract

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#7]
Please add events for `initialize`, `unlockRewardForStaking`, and `makeInstallment` functions.

**Comment by maxaleks** [comment]
Added in https://github.com/poanetwork/dpos-token/commit/ba2c8663375bbba843c0c32d035a873b73297e64

**Comment by varasev** [comment]
Please add an unlocked amount to the `RewardForStakingUnlocked` event.

**Comment by maxaleks** [comment]
Added in https://github.com/poanetwork/dpos-token/commit/a363641e18fab8df1f802da82a87cba43d2147c6
