### ISSUE TITLE
Suggestion to add `changeAddress` function

### ISSUE THREAD

**Issue by varasev** [poanetwork/dpos-token#8]
Since the installment periods (including cliff) for `xDai Ecosystem Fund` and `xDai Foundation Reward` are relatively long (1-3 years), I'd propose to add `changeAddress` function which would allow changing the address of `xDai Ecosystem Fund` or `xDai Foundation Reward` if needed.

That would be useful for a case of finding some vulnerability in a multisig wallet which would be a cause for changing multisig address to another wallet.

```solidity
event PoolAddressChanged(uint8 indexed pool, address oldAddress, address newAddress);

function changeAddress(uint8 _pool, address _newAddress) external initialized {
    require(_pool == ECOSYSTEM_FUND || _pool == FOUNDATION_REWARD, "wrong pool");
    require(msg.sender == poolAddress[_pool]);
    emit PoolAddressChanged(_pool, poolAddress[_pool], _newAddress);
    poolAddress[_pool] = _newAddress;
}
```

@igorbarinov do you agree we should have this in the `Distribution` contract?

**Comment by igorbarinov** [comment]
I agree.

**Comment by maxaleks** [comment]
Added in https://github.com/poanetwork/dpos-token/commit/f541939f8b8cedfdc59a1ed4d272140bc7e234e9
